### ISSUE TITLE
Annotation

### ISSUE THREAD

**Issue by Jeff-alytics** [bhelx/nola-neighborhood-annotation#1]
Is there a downloadable version with the neighborhoods annotated? Doesn't seem attached but that may be because I'm a newbie

**Comment by bhelx** [comment]
@jeffmasher sorry, this is actually my fault. I accidentally uploaded a 0MB file. Forgot to add the changes. I have fixed this.

Go to this url https://github.com/bhelx/nola-neighborhood-annotation/blob/master/data/calls_for_service/2016_annotated.csv

Right click on the `Download` button and choose `Save Link As`or whatever your browser uses to save a link as a file.

<img width="568" alt="screen shot 2016-08-10 at 1 32 46 pm" src="https://cloud.githubusercontent.com/assets/185919/17565943/131d8068-5eff-11e6-9f4d-016886ab94e6.png">

Let me know if that works. Also let me know if you want some other data done and can't run the script yourself. I'd be happy to make a zip file with the other calls for service data.
